name: MinerSimulator
version: '1.0'
main: me.topilov.App
api-version: 1.13
commands:
  eco: {}
  menu: {}
  rebirth: {}
  locations:
    aliases: locks
  level:
    aliases: lvl
  setvalue: {}
  sellall: {}
  bp: {}
  bits: {}
  upgrade: {}
  createnpc: {}
  donate: {}
  test: {}
  top: {}