name: MinerSimulator
version: '${project.version}'
main: me.topilov.App
api-version: 1.13
commands:
  eco: {}
  menu: {}
  rebirth: {}
  locations: {}
  level: {}
  setvalue: {}
  sellall: {}
  bp: {}
  bits: {}
  upgrade: {}
